SELECT p.MOVIENO, P.TITLE, P.RUNTIME, P.TMDB_SCORE, B.LONGDESC 
FROM MOVIE9809 as P 
RIGHT JOIN RATING9809 as B ON P.RATINGCODE = B.RATINGCODE 
WHERE B.LONGDESC LIKE '%recommended%'
or  P.TMDB_ID LIKE '%44%'
OR P.TITLE LIKE '%t%'


